### ISSUE TITLE
Code release date

### ISSUE THREAD

**Issue by pipme** [theodeprelle/AtlasNetV2#1]
Hi Theo,

Your work is very insteresting. I'd like to ask when the code will be available? Thanks.

**Comment by TheoDEPRELLE** [comment]
Hi,

The code will be online next Tuesday,

Thanks you!

Best,

Théo

**Comment by theodeprelle** [comment]
Hi,

The code as been released today, we have simplified and cleaned the lab version and we are in the process of retraining the models to verify that the performances match the paper numbers. If you find anything wrong please let me know.
