### ISSUE TITLE
The question about initialization of 'rand_grid' in the ./auxiliary/model.py

### ISSUE THREAD

**Issue by tommaoer** [theodeprelle/AtlasNetV2#2]
I have a question. In the file 'model.py', line 378,379, why the variable 'rand_grid' is initialized to uniform(0,1) before it is initialized to zero. What is the reason? 
Thanks!

**Comment by theodeprelle** [comment]
Hi,
Indeed there was a bug. You should zero the values of the last column starting from 2. I've updated the code today and it should work fine now. Thanks for letting me know this!

**Comment by tommaoer** [comment]
Thanks very much!
