### ISSUE TITLE
How to Generate 16384 points for Point Translation Module?

### ISSUE THREAD

**Issue by hzxie** [theodeprelle/AtlasNetV2#3]
As discussed in https://github.com/ThibaultGROUEIX/AtlasNet/issues/42, I want to upsample the results of the point translation module.
Since this module takes a fixed number of points into the network. I don't know whether training a new model taking 16384 points as input is justifiable to compare with our method.

**Comment by theodeprelle** [comment]
Hi,

You're right there it is impossible to upsample the results with the current version. I would retrain the network if I were you.

**Comment by hzxie** [comment]
@TheoDEPRELLE 
Thank you for your response.
