### ISSUE TITLE
error in nnd updateOutput: invalid device function

### ISSUE THREAD

**Issue by patrick100** [theodeprelle/AtlasNetV2#5]
I have the following error 
![Screenshot from 2020-02-14 21-12-45](https://user-images.githubusercontent.com/11828267/74580136-c8ad0300-4f6e-11ea-874c-4fa3c2480325.png)

**Comment by LeiYangJustin** [comment]
When I do python setup.py install with cuda 10.2, I got the same error.
Then I switch to cuda 9.2, the problem solved. Not sure if cuda version is the key issue.
