### ISSUE TITLE
Unable to download shapenet data

### ISSUE THREAD

**Issue by brjathu** [theodeprelle/AtlasNetV2#9]
Hi,

I am trying to download data form download.sh script. But it is giving 404 error.

--2020-12-01 14:38:25--  https://cloud.enpc.fr/s/j2ECcKleA1IKNzk/download
Resolving cloud.enpc.fr (cloud.enpc.fr)... 195.221.193.80
Connecting to cloud.enpc.fr (cloud.enpc.fr)|195.221.193.80|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-01 14:38:26 ERROR 404: Not Found.

could you please provide an alternative link?

**Comment by CRISZJ** [comment]
i also meet this problem. have you solved it?

**Comment by CRISZJ** [comment]
could you please provide more details about your dataset?

**Comment by ThibaultGROUEIX** [comment]
Dear @brjathu , @CRISZJ 

I've updated `download.sh`, i have no idea why the link changed on our side.

Best,
Thibault

**Comment by khalilsarwari** [comment]
Hi @ThibaultGROUEIX , I think the third updated link is still pointing to `ShapeNetCorev2Normalized` when it should be pointing to `ShapeNetRendering` instead?

Running download.sh only gave me `customShapeNet`  and  `ShapeNetCorev2Normalized`

**Comment by orenkatzir** [comment]
Same problem here - the intended link to download ShapeNetCorev2Normalized seems to be broken, and the link for the renderedImages is pointing to ShapeNetCorev2Normalized.

**Comment by chunyinhuang** [comment]
Still having the same problem as @orenkatzir 
"  the intended link to download ShapeNetCorev2Normalized seems to be broken, and the link for the renderedImages is pointing to ShapeNetCorev2Normalized. "
Has anyone figured out how to solve it?

**Comment by RahulSajnani** [comment]
Did anyone solve this issue? The second link seems to be broken even now.

**Comment by ThibaultGROUEIX** [comment]
Hi @RahulSajnani ,

You can check out : https://github.com/ThibaultGROUEIX/AtlasNet/issues/61

Best regards,
Thibault

**Comment by darrenjkt** [comment]
Hi @ThibaultGROUEIX,

The link given for the AtlasNet page only has data download links for ShapeNetV1. Do you have a similar link to ShapeNetV2?

**Comment by ThibaultGROUEIX** [comment]
Hi @darrenjkt 
Did you try this link ? https://github.com/ThibaultGROUEIX/AtlasNet#a-note-on-data
Best regards,

**Comment by pxing6** [comment]
can you upgrade download.sh? I can not download ShapeNetV2
